### ISSUE TITLE
Source package on pypi missing requirements.txt

### ISSUE THREAD

**Issue by qwertos** [Kaleidophon/deep-significance#12]

**Comment by Kaleidophon** [comment]
Hey! 

Thanks for creating the issue. I just checked and it is indeed not included by default; but could you also tell me more about the use case for this (just really asking out of curiosity)? 
I have seen that the requirements are also saved in `deepsig.egg-info/requires.txt`.

**Comment by Kaleidophon** [comment]
Closed for now!

**Comment by qwertos** [comment]
Sorry, it's taken me a bit to get back to this. Because of the missing requirements.txt, the source package fails to install due to [line 6-7 in setup.py](https://github.com/Kaleidophon/deep-significance/blob/489a6d709737af2b01e4bc05b0ee90be011eb373/setup.py#L6).

**Comment by Kaleidophon** [comment]
Sorry, no problem! Could you describe to me the process on how you would exactly install the package? As far as my knowledge goes, you would either install it via `pip3 install deepsig` or `git clone` and then calling `setup.py`; both ways should work at the current stage.

**Comment by qwertos** [comment]
I'm currently working on getting this packaged up for inclusion in [Spack](http://github.com/spack/spack). While we can pull from GitHub, Spack highly prefers to build packages from source acquired from pypi for reproducibility reasons.

**Comment by Kaleidophon** [comment]
I added a `MANIFEST.in` to the repo and bumped up the version to `1.2.1`. Downloading the files from pypi also showed me that it included the `requirements.txt` now. Could you verify this with your Spack setup and close the issue if it works?
