### ISSUE TITLE
Sample-level random seed test

### ISSUE THREAD

**Issue by tresiwald** [Kaleidophon/deep-significance#3]
Hi, 

First of all, thanks a lot for your work. It is exactly what I was looking for :)

I wondered if it is possible to compare multiple runs of the two models, A and B, on sample level rather than on score level? So let's say you trained each model five times with different random seeds. Does it make sense that two tests each run of A against each run of B and then average all the epsilons?

**Comment by Kaleidophon** [comment]
Thank you very much for your interest! :-) The setup itself is very much possible and precisely the one described in the [Readme here](https://github.com/Kaleidophon/deep-significance#scenario-3---comparing-sample-level-scores), so you should retain the pair-wise epsilon_min scores and then control using the Bonferroni correction by dividing the original confidence level by the number of comparisons. To aggregate the epsilon_min scores to come to a conclusion about A vs. B, I would _not_ choose to average them, but rather report how many of them yielded a significant result (although there might be a better way to do this that I am not aware of). 

Let me know if that answers your question!

**Comment by Kaleidophon** [comment]
Closed unless there is any follow-up question.
